name: Node.js tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:  [14.x]

    steps:
    - name: Run tests
      working-directory: ../../server
    - run: npm i
    - run: npm run test
